from __future__ import annotations

import argparse
import sys
from pathlib import Path

from scripts.crop_hand_roi_cards import parse_crop_size
from scripts.replay_phase2 import parse_roi_box
from src.pipeline import (
    DEFAULT_APP_NAME,
    DEFAULT_CARD_COUNT,
    DEFAULT_CONFIDENCE_THRESHOLD,
    DEFAULT_CROP_SIZE,
    DEFAULT_ROI_BOX,
    DEFAULT_START_X,
    DEFAULT_START_Y,
    DEFAULT_STEP_X,
    ObservationStabilizer,
    Phase3Runtime,
    RuntimeCaptureError,
    RuntimeSettings,
    WindowLookupError,
    calibrate_roi,
    find_window,
    format_runtime_event,
    load_runtime_config,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run Phase 3 fixed-ROI Mac screen runtime.")
    parser.add_argument("--config", help="Runtime config JSON generated by scripts.calibrate_phase3_roi.")
    parser.add_argument("--model", help="PyTorch checkpoint path.")
    parser.add_argument("--device", help="auto, cpu, mps, or cuda.")
    parser.add_argument("--roi-box", help="Screen ROI box: left,top,right,bottom.")
    parser.add_argument("--count", type=int, help="Number of hand cards to crop from ROI.")
    parser.add_argument("--start-x", type=int)
    parser.add_argument("--start-y", type=int)
    parser.add_argument("--step-x", type=int)
    parser.add_argument("--crop-size", type=parse_crop_size)
    parser.add_argument("--last-play", help="Previous play, empty means lead play.")
    parser.add_argument("--confidence-threshold", type=float)
    parser.add_argument("--stability-window", type=int, help="Number of recent frames used for rank voting; 1 disables stabilization.")
    parser.add_argument("--app-name", default=None, help="macOS process/app name used with --auto-window.")
    parser.add_argument("--auto-window", action="store_true", help="Read the app window and derive ROI before capture.")
    parser.add_argument("--interval", type=float, default=1.0, help="Seconds between frames.")
    parser.add_argument("--max-frames", type=int, default=None, help="Stop after N frames; omit for continuous runtime.")
    parser.add_argument("--log-file", help="JSONL runtime log path.")
    parser.add_argument("--no-clear", action="store_true", help="Do not clear the terminal between frames.")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        config = load_runtime_config(Path(args.config)) if args.config else None
        app_name = args.app_name or (config.app_name if config and config.app_name else DEFAULT_APP_NAME)
        roi_box = _coalesce_roi_box(args.roi_box, config.roi_box if config else None)
        count = _coalesce(args.count, config.count if config else None, DEFAULT_CARD_COUNT)
        start_x = _coalesce(args.start_x, config.start_x if config else None, DEFAULT_START_X)
        start_y = _coalesce(args.start_y, config.start_y if config else None, DEFAULT_START_Y)
        step_x = _coalesce(args.step_x, config.step_x if config else None, DEFAULT_STEP_X)
        crop_size = _coalesce(args.crop_size, config.crop_size if config else None, DEFAULT_CROP_SIZE)
        if args.auto_window:
            calibration = calibrate_roi(
                find_window(app_name),
                count=count,
                start_x=start_x,
                start_y=start_y,
                step_x=step_x,
                crop_size=crop_size,
            )
            roi_box = calibration.roi_box
        settings = RuntimeSettings(
            model_path=Path(_coalesce(args.model, str(config.model_path) if config and config.model_path else None, "models/card_cnn.pt")),
            device_name=_coalesce(args.device, config.device_name if config else None, "auto"),
            roi_box=roi_box,
            count=count,
            start_x=start_x,
            start_y=start_y,
            step_x=step_x,
            crop_size=crop_size,
            confidence_threshold=_coalesce(args.confidence_threshold, config.confidence_threshold if config else None, DEFAULT_CONFIDENCE_THRESHOLD),
            last_play=_coalesce(args.last_play, config.last_play if config else None, ""),
            log_file=Path(_coalesce(args.log_file, str(config.log_file) if config and config.log_file else None, "logs/phase3_runtime.jsonl")),
            stability_window=_coalesce(args.stability_window, config.stability_window if config else None, 3),
        )
        stabilizer = ObservationStabilizer(settings.stability_window) if settings.stability_window > 1 else None
        runtime = Phase3Runtime(settings, stabilizer=stabilizer)
        for event in runtime.run_loop(max_frames=args.max_frames, interval=args.interval):
            if not args.no_clear:
                print("\033[2J\033[H", end="")
            print(format_runtime_event(event), flush=True)
    except KeyboardInterrupt:
        print("\nPhase 3 runtime stopped.")
        return 0
    except RuntimeCaptureError as exc:
        print(f"截图错误: {exc}", file=sys.stderr)
        return 2
    except WindowLookupError as exc:
        print(f"窗口错误: {exc}", file=sys.stderr)
        return 2
    except FileNotFoundError as exc:
        print(f"文件错误: {exc}", file=sys.stderr)
        return 2
    except ValueError as exc:
        print(f"运行参数错误: {exc}", file=sys.stderr)
        return 2
    return 0


def _coalesce(*values):
    for value in values:
        if value is not None:
            return value
    raise ValueError("At least one value is required")


def _coalesce_roi_box(value: str | None, config_value: tuple[int, int, int, int] | None) -> tuple[int, int, int, int]:
    if value is not None:
        return parse_roi_box(value)
    if config_value is not None:
        return config_value
    return DEFAULT_ROI_BOX


if __name__ == "__main__":
    raise SystemExit(main())
